### ISSUE TITLE
Invalid regex issue

### ISSUE THREAD

**Issue by Jason954** [aussedatlo/banalize#22]
### Description

There is a syntax error in the regular expression used in the `extractIp` function within the api package. The error message indicates that the regular expression is invalid. When it's invalid, the package crash.

### Error Log

``` text/plain
@banalize/api:dev: /home/jason/Nas/banalize/packages/shared-utils/dist/index.js:7
@banalize/api:dev:     const regex = new RegExp(modifiedPattern);
@banalize/api:dev:                   ^
@banalize/api:dev: 
@banalize/api:dev: SyntaxError: Invalid regular expression: /^*.(\b(?:[0-9]{1,3}\.){3}[0-9]{1,3}\b)$/: Nothing to repeat
@banalize/api:dev:     at new RegExp (<anonymous>)
@banalize/api:dev:     at extractIp (/home/jason/Nas/banalize/packages/shared-utils/dist/index.js:7:19)
@banalize/api:dev:     at /home/jason/Nas/banalize/apps/api/dist/watchers/services/docker-watcher.service.js:52:61
@banalize/api:dev:     at Array.forEach (<anonymous>)
@banalize/api:dev:     at DockerWatcherService.onData (/home/jason/Nas/banalize/apps/api/dist/watchers/services/docker-watcher.service.js:49:18)
@banalize/api:dev:     at IncomingMessage.emit (node:events:519:28)
@banalize/api:dev:     at addChunk (node:internal/streams/readable:559:12)
@banalize/api:dev:     at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
@banalize/api:dev:     at Readable.push (node:internal/streams/readable:390:5)
@banalize/api:dev:     at HTTPParser.parserOnBody (node:_http_common:131:24)
@banalize/api:dev: 
@banalize/api:dev: Node.js v20.13.1
```

**Comment by aussedatlo** [comment]
Should be fixed with the PR #23
